eureka:
  client:
    serviceUrl:
      defaultZone: http://104.197.130.41:8762/eureka

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

spring:
  datasource:
    url: jdbc:postgresql://database-2.cn6kg88w28oy.eu-north-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: Root1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  data: ## default it uses host: localhost and port: 6379
    redis:
      host: localhost
      port: 6379
  cache: ## this for time to live of data which is stored to redis
    redis:
      time-to-live: 10m

springdoc:
  api-docs:
    path: /api/v1/e/api-docs
  swagger-ui:
    path: /api/v1/e/swagger-ui.html
    
logging:
  level:
    root: warn
  file:
    name: figure-this-shit-out.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 10
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"